# Generated by Django 3.2.9 on 2021-11-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempUser',
            fields=[
                ('tempname', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('emailid', models.EmailField(max_length=80)),
                ('qwertypass', models.CharField(max_length=20)),
                ('unique', models.TextField(help_text='Unique ID for this person', primary_key=True, serialize=False)),
            ],
        ),
    ]
